<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Pearson’s Chi-squared test | UCSD Psyc 201ab / CSS 205 / Psyc 193</title>
  <meta name="description" content="This is the class website and lecture notes for psyc 201ab and CSS 205" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Pearson’s Chi-squared test | UCSD Psyc 201ab / CSS 205 / Psyc 193" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the class website and lecture notes for psyc 201ab and CSS 205" />
  <meta name="github-repo" content="UCSD-PSYC201/website" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Pearson’s Chi-squared test | UCSD Psyc 201ab / CSS 205 / Psyc 193" />
  
  <meta name="twitter:description" content="This is the class website and lecture notes for psyc 201ab and CSS 205" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="binomial-test.html"/>
<link rel="next" href="bivariate.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="course-syllabus.html"><a href="course-syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="course-syllabus.html"><a href="course-syllabus.html#instructors"><i class="fa fa-check"></i>Instructors</a></li>
<li class="chapter" data-level="" data-path="course-syllabus.html"><a href="course-syllabus.html#class-meetings"><i class="fa fa-check"></i>Class meetings</a></li>
<li class="chapter" data-level="" data-path="course-syllabus.html"><a href="course-syllabus.html#grading"><i class="fa fa-check"></i>Grading</a></li>
<li class="chapter" data-level="" data-path="course-syllabus.html"><a href="course-syllabus.html#class-resources"><i class="fa fa-check"></i>Class Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html"><i class="fa fa-check"></i>201a Schedule</a>
<ul>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-0-introduction"><i class="fa fa-check"></i>Week 0: Introduction</a></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-1-data"><i class="fa fa-check"></i>Week 1: Data</a></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-2-visualization"><i class="fa fa-check"></i>Week 2: Visualization</a></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-3-theoretical-foundations"><i class="fa fa-check"></i>Week 3: Theoretical foundations</a></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-4-linear-model-regression"><i class="fa fa-check"></i>Week 4: Linear model: Regression</a></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-5-linear-model-multiple-regression"><i class="fa fa-check"></i>Week 5: Linear model: Multiple regression</a></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-6-linear-model-categorical-predictors"><i class="fa fa-check"></i>Week 6: Linear model: Categorical predictors</a></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-7-linear-model-ancova-diagnostics"><i class="fa fa-check"></i>Week 7: Linear model: ANCOVA, diagnostics</a></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-8-linear-model-linearizing-transforms"><i class="fa fa-check"></i>Week 8: Linear model: Linearizing transforms</a></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-9-covarying-errors-repeated-measures-random-effects"><i class="fa fa-check"></i>Week 9: Covarying errors (repeated measures / random effects)</a></li>
<li class="chapter" data-level="" data-path="course-201a.html"><a href="course-201a.html#week-10-review-and-preview"><i class="fa fa-check"></i>Week 10: Review and preview</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html"><i class="fa fa-check"></i>Projects</a>
<ul>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#examples-of-this-sort-of-thing"><i class="fa fa-check"></i>Examples of this sort of thing</a></li>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#a"><i class="fa fa-check"></i>201a</a>
<ul>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#a-timeline"><i class="fa fa-check"></i>201a Timeline</a></li>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#groups"><i class="fa fa-check"></i>Groups</a></li>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#a-project-plan"><i class="fa fa-check"></i>201a Project plan</a></li>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#a-preliminary-data-summaries"><i class="fa fa-check"></i>201a Preliminary data summaries</a></li>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#a-write-ups"><i class="fa fa-check"></i>201a Write-ups</a></li>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#a-presentation"><i class="fa fa-check"></i>201a Presentation</a></li>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#a-group-evaluation"><i class="fa fa-check"></i>201a Group-evaluation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#b"><i class="fa fa-check"></i>201b</a></li>
<li class="chapter" data-level="" data-path="course-projects.html"><a href="course-projects.html#data-sources"><i class="fa fa-check"></i>Data sources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-homework.html"><a href="r-homework.html"><i class="fa fa-check"></i>R homework</a>
<ul>
<li class="chapter" data-level="" data-path="r-homework.html"><a href="r-homework.html#grading-1"><i class="fa fa-check"></i>Grading</a></li>
<li class="chapter" data-level="" data-path="r-homework.html"><a href="r-homework.html#collaboration"><i class="fa fa-check"></i>Collaboration</a></li>
<li class="chapter" data-level="" data-path="r-homework.html"><a href="r-homework.html#submitting-r-assignments"><i class="fa fa-check"></i>Submitting R Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="r-homework.html"><a href="r-homework.html#writing-r-scripts"><i class="fa fa-check"></i>Writing R scripts</a></li>
<li class="chapter" data-level="" data-path="r-homework.html"><a href="r-homework.html#submitting-your-assignment"><i class="fa fa-check"></i>Submitting your assignment</a></li>
<li class="chapter" data-level="" data-path="r-homework.html"><a href="r-homework.html#additional-resources."><i class="fa fa-check"></i>Additional resources.</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Notes</b></span></li>
<li class="chapter" data-level="" data-path="R-start.html"><a href="R-start.html"><i class="fa fa-check"></i>Getting started with R</a>
<ul>
<li class="chapter" data-level="" data-path="R-start.html"><a href="R-start.html#R-install"><i class="fa fa-check"></i>Installing R</a>
<ul>
<li class="chapter" data-level="" data-path="R-start.html"><a href="R-start.html#packages"><i class="fa fa-check"></i>Packages</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="R-start.html"><a href="R-start.html#R-intro"><i class="fa fa-check"></i>Introduction to R</a>
<ul>
<li class="chapter" data-level="" data-path="R-start.html"><a href="R-start.html#getting-started"><i class="fa fa-check"></i>Getting started</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="R-start.html"><a href="R-start.html#better-data-analysis-code."><i class="fa fa-check"></i>Better data analysis code.</a></li>
<li class="chapter" data-level="" data-path="R-start.html"><a href="R-start.html#using-r-markdown"><i class="fa fa-check"></i>Using R-markdown</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html"><i class="fa fa-check"></i>Visualizations</a>
<ul>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#general-rules-for-scientific-data-visualization."><i class="fa fa-check"></i>General rules for scientific data visualization.</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#picking-a-plot-whats-convention"><i class="fa fa-check"></i>Picking a plot (what’s convention)</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#categorical-0"><i class="fa fa-check"></i>Categorical ~ 0</a>
<ul>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#pie-chart"><i class="fa fa-check"></i>Pie chart</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#stacked-area"><i class="fa fa-check"></i>Stacked area</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#numerical-0"><i class="fa fa-check"></i>numerical ~ 0</a>
<ul>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#histogram-density"><i class="fa fa-check"></i>Histogram &amp; density</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#numerical-categorical"><i class="fa fa-check"></i>numerical ~ categorical</a>
<ul>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#bar-plot-with-error-bars"><i class="fa fa-check"></i>Bar plot with error bars</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#jittered-data-points."><i class="fa fa-check"></i>Jittered data points.</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#violaviolin-plot"><i class="fa fa-check"></i>Viola/Violin plot</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#box-and-whiskers-plot"><i class="fa fa-check"></i>Box and whiskers plot</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#overlayed-densities"><i class="fa fa-check"></i>Overlayed densities</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#empirical-cumulative-distribution"><i class="fa fa-check"></i>Empirical cumulative distribution</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#comparisons"><i class="fa fa-check"></i>Comparisons</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#recommendations"><i class="fa fa-check"></i>Recommendations</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#numerical-numerical-2-x-numerical-0"><i class="fa fa-check"></i>numerical ~ numerical (2 x numerical ~ 0)</a>
<ul>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#scatter-and-heatmap"><i class="fa fa-check"></i>Scatter and heatmap</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#conditional-means"><i class="fa fa-check"></i>Conditional means</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#numerical-numerical-categorical"><i class="fa fa-check"></i>numerical ~ numerical + categorical</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#categorical-numerical"><i class="fa fa-check"></i>categorical ~ numerical</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#x-categorical-and-categorical-categorical"><i class="fa fa-check"></i>2 x categorical and categorical ~ categorical</a>
<ul>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#heatmap"><i class="fa fa-check"></i>Heatmap</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#categorical-categorical"><i class="fa fa-check"></i>categorical ~ categorical</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#extra-plot-notes."><i class="fa fa-check"></i>Extra plot notes.</a>
<ul>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#numerical-2-x-categorical"><i class="fa fa-check"></i>numerical ~ 2 x categorical</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html#bin-width-and-bandwidths"><i class="fa fa-check"></i>bin width and bandwidths</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i>Probability</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-terms"><i class="fa fa-check"></i>Probability terms</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#absolute-probability-statements-prob"><i class="fa fa-check"></i>Absolute probability statements {prob}</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-comparisons"><i class="fa fa-check"></i>Probability comparisons</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#proportional-magnitudes-and-confusion"><i class="fa fa-check"></i>Proportional magnitudes and confusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-foundations"><i class="fa fa-check"></i>Foundations of probability</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#set-notation-for-combinations-of-outcomes."><i class="fa fa-check"></i>Set notation for combinations of outcomes.</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#basic-probability-definition-and-axioms"><i class="fa fa-check"></i>Basic probability definition and axioms</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#events-and-the-rules-of-probability."><i class="fa fa-check"></i>Events and the rules of probability.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-conditional"><i class="fa fa-check"></i>Conditional probability and Bayes</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#chain-rule"><i class="fa fa-check"></i>Chain rule</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#partitions-and-total-probability"><i class="fa fa-check"></i>Partitions and total probability</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#bayes-rule"><i class="fa fa-check"></i>Bayes’ rule</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-simulations"><i class="fa fa-check"></i>Simulation, Sampling and Monte Carlo.</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#sampling-long-run-frequency-and-the-law-of-large-numbers."><i class="fa fa-check"></i>Sampling, long-run frequency, and the law of large numbers.</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#sampling-to-estimate-event-probabilities."><i class="fa fa-check"></i>Sampling to estimate event probabilities.</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-of-a-conjunction-of-events"><i class="fa fa-check"></i>Probability of a conjunction of events</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#sampling-to-get-probability-of-disjunction"><i class="fa fa-check"></i>Sampling to get probability of disjunction</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#sampling-to-calculate-conditional-probability"><i class="fa fa-check"></i>Sampling to calculate conditional probability</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-rv-functions"><i class="fa fa-check"></i>Distribution functions: PDF, CDF, Quantile</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-distribution-mass-and-density-functions-p.d.f."><i class="fa fa-check"></i>Probability distribution (mass and density) functions (p.d.f.)</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#cumulative-distribution-functions-c.d.f."><i class="fa fa-check"></i>Cumulative distribution functions (c.d.f.)</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#quantile-functions-inverse-cdf."><i class="fa fa-check"></i>Quantile functions (inverse CDF).</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-expectation"><i class="fa fa-check"></i>Expectation and moments</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#there-are-a-few-useful-properties-about-how-the-mean-variance-skewness-and-excess-kurtosis-behave-under-various-operations"><i class="fa fa-check"></i>There are a few useful properties about how the Mean, Variance, Skewness, and Excess Kurtosis behave under various operations:</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#probability-clt"><i class="fa fa-check"></i>Central limit theorem and the normal distribution</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#requirements-for-clt-to-hold"><i class="fa fa-check"></i>Requirements for CLT to hold</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#normal-distribution"><i class="fa fa-check"></i>Normal distribution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html"><i class="fa fa-check"></i>Foundations of Statistics</a>
<ul>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#NHST-simulation"><i class="fa fa-check"></i>Frequentist statistics via simulation</a>
<ul>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#critical-values-alpha-power"><i class="fa fa-check"></i>Critical values, alpha, power</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#setting-up-the-alternate-hypothesis"><i class="fa fa-check"></i>Setting up the “Alternate hypothesis”</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#figuring-out-power"><i class="fa fa-check"></i>Figuring out “power”</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#figuring-out-alpha"><i class="fa fa-check"></i>Figuring out “alpha”</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#showing-alpha-power"><i class="fa fa-check"></i>Showing alpha, power</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#figuring-out-the-critical-value."><i class="fa fa-check"></i>Figuring out the critical value.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#NHST-sampling"><i class="fa fa-check"></i>Sampling distributions</a>
<ul>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#tl-dr."><i class="fa fa-check"></i>TL; DR.</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#logic"><i class="fa fa-check"></i>Logic</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#expectation-about-the-sampling-distribution-of-the-sample-mean."><i class="fa fa-check"></i>Expectation about the sampling distribution of the sample mean.</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#standard-error-of-the-sample-mean"><i class="fa fa-check"></i>Standard error (of the sample mean)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#NHST-basics-normal"><i class="fa fa-check"></i>Statistics via the Normal distribution</a>
<ul>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#normal-null-hypothesis-significance-testing-nhst"><i class="fa fa-check"></i>(Normal) Null hypothesis significance testing (NHST)</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#normal-tests-with-sample-means"><i class="fa fa-check"></i>Normal tests with sample means</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#z-scores-and-z-tests"><i class="fa fa-check"></i>Z-scores and Z-tests</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#z-tests"><i class="fa fa-check"></i>Z-tests</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#normal-confidence-intervals-on-the-sample-mean"><i class="fa fa-check"></i>(Normal) Confidence intervals on the sample mean</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#what-are-these-percents-and-probabilities"><i class="fa fa-check"></i>What are these percents and probabilities?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#nhst-theory-normal"><i class="fa fa-check"></i>Null hypothesis significance testing</a>
<ul>
<li><a href="NHST.html#type-1-error-rate-alpha-alpha">Type 1 error rate: alpha (<span class="math inline">\(\alpha\)</span>)</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#the-alternate-model"><i class="fa fa-check"></i>The “alternate model”</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#effect-size"><i class="fa fa-check"></i>Effect size</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#calculating-power-from-effect-size"><i class="fa fa-check"></i>Calculating power from effect size</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#visualizing-alpha-and-power"><i class="fa fa-check"></i>Visualizing alpha and power</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#how-power-changes."><i class="fa fa-check"></i>How power changes.</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#calculating-n-for-a-desired-level-of-power."><i class="fa fa-check"></i>Calculating n for a desired level of power.</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#sign-and-magnitude-errors."><i class="fa fa-check"></i>Sign and magnitude errors.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#theory-binomial"><i class="fa fa-check"></i>Binomial: Probability to statistics</a>
<ul>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#data-description-summary"><i class="fa fa-check"></i>Data description / summary</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#estimation"><i class="fa fa-check"></i>Estimation</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#null-hypothesis-significance-testing-nhst"><i class="fa fa-check"></i>Null Hypothesis Significance testing (NHST)</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#model-selection"><i class="fa fa-check"></i>Model selection</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#t-distribution"><i class="fa fa-check"></i>t-distribution</a>
<ul>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#tl-dr.-1"><i class="fa fa-check"></i>TL; DR.</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#sampling-distribution-of-sample-variance-and-t-statistic"><i class="fa fa-check"></i>Sampling distribution of sample variance, and t-statistic</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#sample-variance"><i class="fa fa-check"></i>Sample variance</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#sampling-distribution-of-the-sample-variance"><i class="fa fa-check"></i>Sampling distribution of the sample variance</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#sampling-distribution-of-t-statistic"><i class="fa fa-check"></i>Sampling distribution of t-statistic</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#t-distribution-1"><i class="fa fa-check"></i>T-distribution</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#degrees-of-freedom."><i class="fa fa-check"></i>Degrees of freedom.</a></li>
<li class="chapter" data-level="" data-path="NHST.html"><a href="NHST.html#summary."><i class="fa fa-check"></i>Summary.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="t-tests.html"><a href="t-tests.html"><i class="fa fa-check"></i>(Student’s) t-tests</a>
<ul>
<li class="chapter" data-level="" data-path="t-tests.html"><a href="t-tests.html#sample-t-test"><i class="fa fa-check"></i>1-sample t-test</a></li>
<li class="chapter" data-level="" data-path="t-tests.html"><a href="t-tests.html#paired-repeated-measures-t-test"><i class="fa fa-check"></i>Paired / repeated-measures t-test</a></li>
<li class="chapter" data-level="" data-path="t-tests.html"><a href="t-tests.html#sample-presumed-equal-variance-t-test"><i class="fa fa-check"></i>2-sample, presumed equal variance, t-test</a></li>
<li class="chapter" data-level="" data-path="t-tests.html"><a href="t-tests.html#sample-unequal-variance-t-test"><i class="fa fa-check"></i>2-sample, unequal variance, t-test</a></li>
<li class="chapter" data-level="" data-path="t-tests.html"><a href="t-tests.html#power-calculations."><i class="fa fa-check"></i>Power calculations.</a></li>
<li class="chapter" data-level="" data-path="t-tests.html"><a href="t-tests.html#summary-of-tests-for-the-mean-and-effect-sizes"><i class="fa fa-check"></i>Summary of tests for the mean and effect sizes</a></li>
<li class="chapter" data-level="" data-path="t-tests.html"><a href="t-tests.html#math."><i class="fa fa-check"></i>Math.</a>
<ul>
<li class="chapter" data-level="" data-path="t-tests.html"><a href="t-tests.html#math-behind-2-sample-equal-variance-t-test"><i class="fa fa-check"></i>Math behind 2-sample equal variance t-test</a></li>
<li class="chapter" data-level="" data-path="t-tests.html"><a href="t-tests.html#math-behind-unequal-variance-t-test"><i class="fa fa-check"></i>Math behind unequal variance t-test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="binomial-test.html"><a href="binomial-test.html"><i class="fa fa-check"></i>Binomial test.</a>
<ul>
<li class="chapter" data-level="" data-path="binomial-test.html"><a href="binomial-test.html#estimating-proportions."><i class="fa fa-check"></i>Estimating proportions.</a></li>
<li class="chapter" data-level="" data-path="binomial-test.html"><a href="binomial-test.html#sign-test-test-for-percentiles"><i class="fa fa-check"></i>Sign test, test for percentiles</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html"><i class="fa fa-check"></i>Pearson’s Chi-squared test</a>
<ul>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html#goodness-of-fit-test"><i class="fa fa-check"></i>“Goodness of fit” test</a>
<ul>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html#implementation-in-r"><i class="fa fa-check"></i>Implementation in R</a></li>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html#chi-squared-test-calculations"><i class="fa fa-check"></i>Chi-squared test calculations</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html#test-for-independence"><i class="fa fa-check"></i>Test for independence</a>
<ul>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html#implementation-in-r-1"><i class="fa fa-check"></i>Implementation in R</a></li>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html#independence-test-calculations"><i class="fa fa-check"></i>Independence test calculations</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html#more-than-2-way-contingency-table"><i class="fa fa-check"></i>More than 2-way contingency table</a></li>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html#mathematical-rationale"><i class="fa fa-check"></i>Mathematical rationale</a></li>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html#limitations"><i class="fa fa-check"></i>Limitations</a></li>
<li class="chapter" data-level="" data-path="chi-squared.html"><a href="chi-squared.html#fishers-exact-test"><i class="fa fa-check"></i>Fisher’s “exact” test</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html"><i class="fa fa-check"></i>Bivariate linear relationships</a>
<ul>
<li><a href="bivariate.html#linear-relationships"><em>Linear</em> relationships</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#covariance-and-correlation-measuring-the-linear-dependence."><i class="fa fa-check"></i>Covariance and correlation: Measuring the linear dependence.</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#covariance"><i class="fa fa-check"></i>Covariance</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#correlation-coefficient"><i class="fa fa-check"></i>Correlation coefficient</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#ols-regression-predicting-the-mean-of-y-for-a-given-x"><i class="fa fa-check"></i>(OLS) Regression: Predicting the mean of y for a given x</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#difference-between-yx-xy-and-the-principle-component-line"><i class="fa fa-check"></i>Difference between y~x, x~y, and the principle component line</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#partitioning-variance"><i class="fa fa-check"></i>Partitioning variance</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#significance-of-a-linear-relationship."><i class="fa fa-check"></i>Significance of a linear relationship.</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#prediction-from-regression."><i class="fa fa-check"></i>Prediction from regression.</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#bivariate-anscombe"><i class="fa fa-check"></i>Anscombe’s quartet</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#bivariate-covariance"><i class="fa fa-check"></i>Covariance</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#estimating-covariance."><i class="fa fa-check"></i>Estimating covariance.</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#bivariate-correlation"><i class="fa fa-check"></i>Correlation</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#correlation-as-the-slope-of-z-scores"><i class="fa fa-check"></i>Correlation as the slope of z-scores</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#coefficient-of-determination"><i class="fa fa-check"></i>Coefficient of determination</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#bivariate-ols"><i class="fa fa-check"></i>Ordinary Least-Squares (OLS) Regression</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#regression-terminology"><i class="fa fa-check"></i>Regression terminology</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#estimating-the-regression-line."><i class="fa fa-check"></i>Estimating the regression line.</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#standard-errors-of-regression-coefficients"><i class="fa fa-check"></i>Standard errors of regression coefficients</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#confidence-intervals-and-tests-for-regression-coefficients"><i class="fa fa-check"></i>Confidence intervals and tests for regression coefficients</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#bivariate-lines"><i class="fa fa-check"></i>y~x vs x~y vs principle component line</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#bivariate-determination"><i class="fa fa-check"></i>Partitioning variance and the coefficient of determination.</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#calculating-sums-of-squares."><i class="fa fa-check"></i>Calculating sums of squares.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#bivariate-significance"><i class="fa fa-check"></i>Significance of linear relationship.</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#significance-of-slope."><i class="fa fa-check"></i>Significance of slope.</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#significance-of-pairwise-correlation"><i class="fa fa-check"></i>Significance of pairwise correlation</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#significance-of-variance-partition."><i class="fa fa-check"></i>Significance of variance partition.</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#isomorphism-with-one-response-and-one-predictor"><i class="fa fa-check"></i>Isomorphism with one response and one predictor</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#bivariate-prediction"><i class="fa fa-check"></i>Regression prediction.</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#predicting-mean-y-given-x."><i class="fa fa-check"></i>Predicting mean y given x.</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#predicting-new-y-given-x."><i class="fa fa-check"></i>Predicting new y given x.</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#visualizing-the-difference"><i class="fa fa-check"></i>Visualizing the difference</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#bivariate-ols-diagnostics"><i class="fa fa-check"></i>Regression Diagnostics</a>
<ul>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#assumption-relationship-between-y-and-x-is-well-described-by-a-line."><i class="fa fa-check"></i>Assumption: relationship between y and x is well described by a line.</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#assumption-out-estimates-are-not-driven-by-a-few-huge-outliers"><i class="fa fa-check"></i>Assumption: out estimates are not driven by a few huge outliers</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#assumption-errors-are-independent-identically-distributed-normal."><i class="fa fa-check"></i>Assumption: errors are independent, identically distributed, normal.</a></li>
<li class="chapter" data-level="" data-path="bivariate.html"><a href="bivariate.html#testing-assumptions"><i class="fa fa-check"></i>Testing assumptions</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">UCSD Psyc 201ab / CSS 205 / Psyc 193</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chi-squared" class="section level1">
<h1>Pearson’s Chi-squared test</h1>
<p>If we have counts in two categories (e.g. heads or tails; women or men; democrat or republican; etc.) we can test whether the distribution of observations deviates from a null hypothesis distribution via a <a href="#nhst-binomial-test">Binomial test</a> (where the null hypothesis specifies the probability/proportion of “success” (e.g., heads/women/democrats/whatever): the parameter <span class="math inline">\(\theta\)</span> or <span class="math inline">\(p\)</span>).</p>
<p>But what if we have counts in more than two categories? For instance, if we don’t have a bipartisan system, but have, say “Tory”, “Labour”, and “Liberal democrats” (as in the UK some time ago), and want to test the distribution of these political parties to some null hypothesis about the proportion of each that we expect to see (e.g., p=1/3 for all three). I this case, we can no longer do a Binomial test, and we turn instead to (Karl) Pearson’s Chi-squared test (which I will often write as <span class="math inline">\(\chi^2\)</span>).</p>
<p>There are two ways that the Chi-squared test is used:</p>
<ol style="list-style-type: decimal">
<li>comparing the observed distribution to some theoretical distribution pre-specified ahead of time: to test the “Goodness of fit” of the theoretical distribution to the observations;<br />
</li>
<li>testing for “independence” between different factors (which, technically, is just a specific theoretical distribution, with some extra parameters that must be estimated from the data).</li>
</ol>
<p>We will first talk about the practicalities of running a chi-squared test, and then we will talk about the probabilistic rationale for the test, and when that rationale breaks down (and what to do about it).</p>
<div id="goodness-of-fit-test" class="section level2">
<h2>“Goodness of fit” test</h2>
<p>The simplest use of Chi-squared tests is to compare some observed counts to an expected distribution of proportions to assess the “goodness of fit” of the theoretical distribution with the observations.</p>
<p>Let’s say we survey students about their political affiliation. We find: 30 Democrats, 8 Republicans, and 15 Independents. We want to compare to a theoretical (null hypothesis) distribution; according to this null hypothesis, 50% should be Democrats, 30% should be republicans, and 20% should be independents.</p>
<div id="implementation-in-r" class="section level3">
<h3>Implementation in R</h3>
<p>In R we can do this via the <code>chisq.test</code> function, although interfacing with this function can be a bit awkward.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="chi-squared.html#cb303-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">party =</span> <span class="fu">c</span>(<span class="fu">replicate</span>(<span class="dv">30</span>, <span class="st">&quot;democrat&quot;</span>), </span>
<span id="cb303-2"><a href="chi-squared.html#cb303-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">replicate</span>(<span class="dv">8</span>, <span class="st">&quot;republican&quot;</span>), </span>
<span id="cb303-3"><a href="chi-squared.html#cb303-3" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">replicate</span>(<span class="dv">15</span>, <span class="st">&quot;independent&quot;</span>)))</span>
<span id="cb303-4"><a href="chi-squared.html#cb303-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>party)</span></code></pre></div>
<pre><code>## 
##    democrat independent  republican 
##          30          15           8</code></pre>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="chi-squared.html#cb305-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the null hypothesis distribution of categories.</span></span>
<span id="cb305-2"><a href="chi-squared.html#cb305-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">H0.p =</span> <span class="fu">c</span>(<span class="st">&quot;democrat&quot;</span><span class="ot">=</span><span class="fl">0.5</span>, <span class="st">&quot;republican&quot;</span><span class="ot">=</span><span class="fl">0.3</span>, <span class="st">&quot;independent&quot;</span><span class="ot">=</span><span class="fl">0.2</span>))</span></code></pre></div>
<pre><code>##    democrat  republican independent 
##         0.5         0.3         0.2</code></pre>
<p>What we want to do is provide the <em>table</em> summary of the observed categories, and the vector of null hypothesis probabilities to <code>chisq.test</code>; however, we must make sure that their order is the same (which they are not now!). We can do this by indexing with a sorted name vector:</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="chi-squared.html#cb307-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">names</span>(H0.p))</span></code></pre></div>
<pre><code>## [1] &quot;democrat&quot;    &quot;independent&quot; &quot;republican&quot;</code></pre>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="chi-squared.html#cb309-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">sorted.data.table =</span> <span class="fu">table</span>(df<span class="sc">$</span>party)[<span class="fu">sort</span>(<span class="fu">names</span>(H0.p))])</span></code></pre></div>
<pre><code>## 
##    democrat independent  republican 
##          30          15           8</code></pre>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="chi-squared.html#cb311-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">sorted.H0.p =</span> H0.p[<span class="fu">sort</span>(<span class="fu">names</span>(H0.p))])</span></code></pre></div>
<pre><code>##    democrat independent  republican 
##         0.5         0.2         0.3</code></pre>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="chi-squared.html#cb313-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(sorted.data.table, <span class="at">p=</span>sorted.H0.p)</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  sorted.data.table
## X-squared = 6.2138, df = 2, p-value = 0.04474</code></pre>
<p>What we get out here is a <span class="math inline">\(\chi^2\)</span> statistic, a degrees of freedom, and a p-value. To understand what these things are, we need to work through the calculations behind this test.</p>
</div>
<div id="chi-squared-test-calculations" class="section level3">
<h3>Chi-squared test calculations</h3>
<p>The <span class="math inline">\(\chi^2\)</span> statistic is defined as:</p>
<p><span class="math display">\[\chi^2 = \sum\limits_{i=1}^c \frac{(O_i-E_i)^2}{E_i}\]</span></p>
<p>where <span class="math inline">\(c\)</span> is the number of columns (here 3: democrats, republicans, independents);<br />
<span class="math inline">\(O_i\)</span> is the observed count in a given cell;<br />
<span class="math inline">\(E_i\)</span> is the expected count: <span class="math inline">\(E_i = p_i * n\)</span>, where <span class="math inline">\(n\)</span> is the total count from all cells, and <span class="math inline">\(p_i\)</span> is the theoretical expected probability in a given cell.</p>
<p>We can reproduce this calculation in R:</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="chi-squared.html#cb315-1" aria-hidden="true" tabindex="-1"></a>o <span class="ot">=</span> sorted.data.table</span>
<span id="cb315-2"><a href="chi-squared.html#cb315-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> sorted.H0.p</span>
<span id="cb315-3"><a href="chi-squared.html#cb315-3" aria-hidden="true" tabindex="-1"></a>e <span class="ot">=</span> p<span class="sc">*</span><span class="fu">sum</span>(o)</span>
<span id="cb315-4"><a href="chi-squared.html#cb315-4" aria-hidden="true" tabindex="-1"></a>(<span class="at">chi.sq.statistic =</span> <span class="fu">sum</span>((o<span class="sc">-</span>e)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>e))</span></code></pre></div>
<pre><code>## [1] 6.213836</code></pre>
<p>This chi-squared statistic corresponds to the sum of the squared deviations of the obesrved cell counts from the expected (under the null hypothesis) cell counts. Bigger deviations mean that our data are further from the null hypothesis prediction.</p>
<p>Below we show this calculation in tabular form, to clarify how it all works.</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="center">Democrats</th>
<th align="center">Republicans</th>
<th align="center">Independents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">cell (<span class="math inline">\(i\)</span>)</td>
<td align="center">1</td>
<td align="center">2</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="left">Observations (<span class="math inline">\(O_i\)</span>)</td>
<td align="center"><span class="math inline">\(O_1 = 30\)</span></td>
<td align="center"><span class="math inline">\(O_2 = 8\)</span></td>
<td align="center"><span class="math inline">\(O_3 = 15\)</span></td>
</tr>
<tr class="odd">
<td align="left">Null (<span class="math inline">\(H_0\)</span></td>
<td align="center"><span class="math inline">\(p_1 = 0.5\)</span></td>
<td align="center"><span class="math inline">\(p_2 = 0.3\)</span></td>
<td align="center"><span class="math inline">\(p_3 = 0.2\)</span></td>
</tr>
<tr class="even">
<td align="left">n = 53</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="left">Expectation</td>
<td align="center"><span class="math inline">\(E_1 = n*p_1 = 26.5\)</span></td>
<td align="center"><span class="math inline">\(E_2 = n*p_2 = 15.9\)</span></td>
<td align="center"><span class="math inline">\(E_3 = n*p_3 = 10.6\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\((O_i-E_i)\)</span></td>
<td align="center">3.5</td>
<td align="center">-7.9</td>
<td align="center">4.4</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\((O_i-E_i)^2\)</span></td>
<td align="center">12.25</td>
<td align="center">62.41</td>
<td align="center">19.36</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\frac{(O_i-E_i)^2}{E_i}\)</span></td>
<td align="center">0.462264151</td>
<td align="center">3.925157233</td>
<td align="center">1.826415094</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\chi^2 = \sum_i \frac{(O_i-E_i)^2}{E_i}\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\chi^2 = 6.21383648\)</span></td>
</tr>
<tr class="even">
<td align="left">df = c-1</td>
<td align="center"></td>
<td align="center"></td>
<td align="center">df=3-1=2</td>
</tr>
</tbody>
</table>
<p>The degrees of freedom (df) is given by the number of observed counts (3 here), minus the number of parameters estimated from the data to calculate the expected counts, here just one parameter: n, the total count. Consequently, the degrees of freedom will be <span class="math inline">\(df=c-1=2\)</span></p>
<p>Now that we have our <span class="math inline">\(\chi^2\)</span> statistic, we can compare it to the null hypothesis <span class="math inline">\(\chi^2\)</span> distribution with those degrees of freedom, to see if we have sufficiently large deviations from the null hypothesis. Specifically, we do a 1-tail test: looking only at the right tail. We can calculate the p-value in R as:</p>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="chi-squared.html#cb317-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">length</span>(sorted.data.table)<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb317-2"><a href="chi-squared.html#cb317-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">p.value =</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(chi.sq.statistic,df))</span></code></pre></div>
<pre><code>## [1] 0.04473862</code></pre>
<p>Alternatively, we could do the same chi-squared test by finding the critical chi-squared value to reach a particular level of <span class="math inline">\(\alpha\)</span>:</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="chi-squared.html#cb319-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="fl">0.05</span></span>
<span id="cb319-2"><a href="chi-squared.html#cb319-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">chi.sq.crit =</span> <span class="fu">qchisq</span>(<span class="dv">1</span><span class="sc">-</span>alpha,df))</span></code></pre></div>
<pre><code>## [1] 5.991465</code></pre>
<p>We can look at a plot of what all of this is doing by looking at the corresponding chi-squared distribution:</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="chi-squared.html#cb321-1" aria-hidden="true" tabindex="-1"></a>chi.vals <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">10</span>,<span class="at">by=</span><span class="fl">0.01</span>)</span>
<span id="cb321-2"><a href="chi-squared.html#cb321-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">chi=</span>chi.vals,</span>
<span id="cb321-3"><a href="chi-squared.html#cb321-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">p.chi =</span> <span class="fu">dchisq</span>(chi.vals, df),</span>
<span id="cb321-4"><a href="chi-squared.html#cb321-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">more.extreme =</span> <span class="fu">ifelse</span>(chi.vals<span class="sc">&gt;=</span>chi.sq.statistic, <span class="st">&quot;more extreme than observed&quot;</span>, <span class="st">&quot;less extreme than observed&quot;</span>))</span>
<span id="cb321-5"><a href="chi-squared.html#cb321-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x=</span>chi, <span class="at">y=</span>p.chi, <span class="at">fill=</span>more.extreme))<span class="sc">+</span></span>
<span id="cb321-6"><a href="chi-squared.html#cb321-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>()<span class="sc">+</span></span>
<span id="cb321-7"><a href="chi-squared.html#cb321-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span>chi.sq.statistic, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>, <span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb321-8"><a href="chi-squared.html#cb321-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span>chi.sq.crit, <span class="at">color=</span><span class="st">&quot;black&quot;</span>)<span class="sc">+</span></span>
<span id="cb321-9"><a href="chi-squared.html#cb321-9" aria-hidden="true" tabindex="-1"></a>  my_theme</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-156-1.png" width="3000" /></p>
<p>We see that our test statistic (6.21; blue line) is greater than the critical value (5.99; black line); or equivalently, the p-value (area under curve beyond our statistic) is smaller than <span class="math inline">\(\alpha\)</span>, meaning that seeing a chi-squared statistic at least as large as ours from samples from the null hypothesis is sufficiently small for us to reject the null hypothesis. So we do.</p>
<p>In other words, we reject the null hypothesis if our observed counts deviate more from the theoretically expected proportions than could be expected by chance. So, we would interpret this result as the distribution of political affiliations in the students we sampled does not follow our theoretical distribution.</p>
<p>The chi-squared test when used to assess whether observed counts deviate from the null is always one tail – the upper tail. However, the lower tail <em>can</em> be used to test whether there is too <em>little</em> variation around the theoretical distribution (this is rarely done in practice, but may be a useful test to see if data were faked, or if there is voter fraud).</p>
</div>
</div>
<div id="test-for-independence" class="section level2">
<h2>Test for independence</h2>
<p>A very common extension of the “goodness of fit” test is to assess independence in a contingency table.</p>
<p>For instance, lets say we gathered something like the following data (counting how many men and how many women reported a particular color as their favorite – out of a small set):</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="center">Red</th>
<th align="center">Green</th>
<th align="center">Blue</th>
<th align="center">Black</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Men</td>
<td align="center">4</td>
<td align="center">2</td>
<td align="center">9</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="left">Women</td>
<td align="center">3</td>
<td align="center">9</td>
<td align="center">3</td>
<td align="center">4</td>
</tr>
</tbody>
</table>
<p>A chi-squared independence test asks whether the rate at which different colors are selected varies between men and women (or equivalently, whether the population of people who prefer different colors constitutes different proportions of men and women).</p>
<div id="implementation-in-r-1" class="section level3">
<h3>Implementation in R</h3>
<p>First let’s make a data frame of the sort that we would have for these data:</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="chi-squared.html#cb322-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">rbind</span>(<span class="fu">data.frame</span>(<span class="at">sex=</span><span class="st">&quot;male&quot;</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)[<span class="fu">replicate</span>(<span class="dv">4</span>, <span class="dv">1</span>),],</span>
<span id="cb322-2"><a href="chi-squared.html#cb322-2" aria-hidden="true" tabindex="-1"></a>           <span class="fu">data.frame</span>(<span class="at">sex=</span><span class="st">&quot;male&quot;</span>, <span class="at">color=</span><span class="st">&quot;green&quot;</span>)[<span class="fu">replicate</span>(<span class="dv">2</span>, <span class="dv">1</span>),],</span>
<span id="cb322-3"><a href="chi-squared.html#cb322-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">data.frame</span>(<span class="at">sex=</span><span class="st">&quot;male&quot;</span>, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>)[<span class="fu">replicate</span>(<span class="dv">9</span>, <span class="dv">1</span>),],</span>
<span id="cb322-4"><a href="chi-squared.html#cb322-4" aria-hidden="true" tabindex="-1"></a>           <span class="fu">data.frame</span>(<span class="at">sex=</span><span class="st">&quot;male&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>)[<span class="fu">replicate</span>(<span class="dv">2</span>, <span class="dv">1</span>),],</span>
<span id="cb322-5"><a href="chi-squared.html#cb322-5" aria-hidden="true" tabindex="-1"></a>           <span class="fu">data.frame</span>(<span class="at">sex=</span><span class="st">&quot;female&quot;</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)[<span class="fu">replicate</span>(<span class="dv">3</span>, <span class="dv">1</span>),],</span>
<span id="cb322-6"><a href="chi-squared.html#cb322-6" aria-hidden="true" tabindex="-1"></a>           <span class="fu">data.frame</span>(<span class="at">sex=</span><span class="st">&quot;female&quot;</span>, <span class="at">color=</span><span class="st">&quot;green&quot;</span>)[<span class="fu">replicate</span>(<span class="dv">9</span>, <span class="dv">1</span>),],</span>
<span id="cb322-7"><a href="chi-squared.html#cb322-7" aria-hidden="true" tabindex="-1"></a>           <span class="fu">data.frame</span>(<span class="at">sex=</span><span class="st">&quot;female&quot;</span>, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>)[<span class="fu">replicate</span>(<span class="dv">3</span>, <span class="dv">1</span>),],</span>
<span id="cb322-8"><a href="chi-squared.html#cb322-8" aria-hidden="true" tabindex="-1"></a>           <span class="fu">data.frame</span>(<span class="at">sex=</span><span class="st">&quot;female&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>)[<span class="fu">replicate</span>(<span class="dv">4</span>, <span class="dv">1</span>),])</span>
<span id="cb322-9"><a href="chi-squared.html#cb322-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb322-10"><a href="chi-squared.html#cb322-10" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    36 obs. of  2 variables:
##  $ sex  : chr  &quot;male&quot; &quot;male&quot; &quot;male&quot; &quot;male&quot; ...
##  $ color: chr  &quot;red&quot; &quot;red&quot; &quot;red&quot; &quot;red&quot; ...</code></pre>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="chi-squared.html#cb324-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>sex, df<span class="sc">$</span>color)</span></code></pre></div>
<pre><code>##         
##          black blue green red
##   female     4    3     9   3
##   male       2    9     2   4</code></pre>
<p>The independence test takes the table of counts, and returns a chi-squared value to measure how much the observed counts deviate from those expected if the rates were independent.</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="chi-squared.html#cb326-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(df<span class="sc">$</span>sex, df<span class="sc">$</span>color))</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  table(df$sex, df$color)
## X-squared = 8.1782, df = 3, p-value = 0.04247</code></pre>
<p>Understanding how this test is carried out requires that we talk about the calculations that go into it:</p>
</div>
<div id="independence-test-calculations" class="section level3">
<h3>Independence test calculations</h3>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="center">Red</th>
<th align="center">Green</th>
<th align="center">Blue</th>
<th align="center">Black</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Men</td>
<td align="center">4</td>
<td align="center">2</td>
<td align="center">9</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="left">Women</td>
<td align="center">3</td>
<td align="center">9</td>
<td align="center">3</td>
<td align="center">4</td>
</tr>
</tbody>
</table>
<p>We will refer to these observations as <span class="math inline">\(O_{i,j}\)</span> where <span class="math inline">\(i\)</span> indexes the row, and <span class="math inline">\(j\)</span> indexes the column. So the count of women who reported blue as their favorite color would be <span class="math inline">\(O_{2,3}=3\)</span>.</p>
<p>The total count is the sum of the counts in all cells:<br />
<span class="math inline">\(n = \sum_{i=1}^r \sum_{j=1}^c O_{i,j}\)</span><br />
here <span class="math inline">\(n=36\)</span>. (<span class="math inline">\(r\)</span> refers to the number of rows – here 2; <span class="math inline">\(c\)</span> refers to the number of columns – here 4).</p>
<p><strong>Independence</strong> is a theoretical claim about the contingency table. Using the language of probability, it says that the probability of a conjunction should be equal to the product of the marginal probabilities. In other words:<br />
<span class="math inline">\(P(A=a, B=b) = P(A=a)P(B=b)\)</span>.<br />
With respect to our contingency table:<br />
<span class="math inline">\(P(G=\text{men }, C=\text{red}) = P(G=\text{men})P(C=\text{red})\)</span></p>
<p>To calculate the expected counts under the null hypothesis of independence, we first estimate the marginal probabilities (e.g., P(men), P(women), etc.).</p>
<p>We calculate two sets of marginal probabilities, one for the rows, another for the columns (in theory, we could have a higher dimensional contingency table; but in practice they are usually limited to 2D row x column arrangements).</p>
<p>We can calculate the marginal probabilities by summing over rows or columns, respectively:</p>
<p><span class="math inline">\(p_{i,\cdot} = \sum_{j=1}^c O_{i,j} / n\)</span><br />
(e.g., <span class="math inline">\(P(men) = p_{1,\cdot} = (4+2+9+2)/36)\)</span>)</p>
<p><span class="math inline">\(p_{\cdot,j} = \sum_{i=1}^r O_{i,j} / n\)</span><br />
(e.g., <span class="math inline">\(P(green) = p_{\cdot,2} = (2+9)/36)\)</span>)</p>
<p>The “expected” count in each cell will be <span class="math inline">\(E_{i,j} = n p_{i,\cdot} p_{\cdot,j}\)</span>.<br />
The <span class="math inline">\(p_{i,\cdot} p_{\cdot,j}\)</span> is the theoretical prediction of independence, and we multiply by <span class="math inline">\(n\)</span> to get the expected count. Shown in the table below.</p>
<table>
<thead>
<tr class="header">
<th align="left"><span class="math inline">\(E_{i,j}\)</span></th>
<th align="center">Red</th>
<th align="center">Green</th>
<th align="center">Blue</th>
<th align="center">Black</th>
<th align="center"><span class="math inline">\(P_{i,\cdot}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Men</td>
<td align="center">3.3</td>
<td align="center">5.2</td>
<td align="center">5.7</td>
<td align="center">2.8</td>
<td align="center">0.472</td>
</tr>
<tr class="even">
<td align="left">Women</td>
<td align="center">3.7</td>
<td align="center">5.8</td>
<td align="center">6.3</td>
<td align="center">3.2</td>
<td align="center">0.528</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(P_{\cdot,j}\)</span></td>
<td align="center">0.19444</td>
<td align="center">0.30555</td>
<td align="center">0.333</td>
<td align="center">0.1667</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p>Most books skip the step of calculating marginal probabilities for chi-squared tests for independence, and instead expected counts are calculated directly. Note that the expressions are algebraically equivalent. I prefer to expose the step of calculating marginal probabilities for the sake of displaying the logic of the test.</p>
<p><span class="math inline">\(E_{i,j} = \frac{\sum_{a=1}^r O_{a,j} \sum_{b=1}^c O_{i,b}}{n}\)</span></p>
<p>This can be read as (number of observations in the column)*(number of observations in the row)/(number of observations in the total table).</p>
<p>We can now calculate the deviation of each cell:</p>
<p><span class="math inline">\(\frac{(O_{i,j} - E_{i,j})^2}{E_{i,j}}\)</span></p>
<table>
<thead>
<tr class="header">
<th align="left"><span class="math inline">\(\frac{(O_{i,j} - E_{i,j})^2}{E_{i,j}}\)</span></th>
<th align="center">Red</th>
<th align="center">Green</th>
<th align="center">Blue</th>
<th align="center">Black</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Men</td>
<td align="center">0.15</td>
<td align="center">1.96</td>
<td align="center">1.96</td>
<td align="center">0.25</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="left">Women</td>
<td align="center">0.13</td>
<td align="center">1.76</td>
<td align="center">1.75</td>
<td align="center">0.22</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p>The test statistic is the sum of all of these deviations:</p>
<p><span class="math inline">\(\chi^2 = \sum_{i=1}^r \sum_{j=1}^c \frac{(O_{i,j} - E_{i,j})^2}{E_{i,j}}\)</span></p>
<p>In our case the test statistic will be: <span class="math inline">\(\chi^2 = 8.18\)</span>.</p>
<p>The degrees of freedom are again, the number of cells (here 8) minus the number of parameters we estimated from the data: 5 (<span class="math inline">\(n\)</span>, <span class="math inline">\(p_{\cdot,1}\)</span>, <span class="math inline">\(p_{\cdot,2}\)</span>, <span class="math inline">\(p_{\cdot,3}\)</span>, and <span class="math inline">\(p_{1,\cdot}\)</span>).
(note <span class="math inline">\(p_{\cdot,4}=1-p_{\cdot,1}-p_{\cdot,2}-p_{\cdot,3}\)</span>, and <span class="math inline">\(p_{2,\cdot}=1-p_{1,\cdot}\)</span>, so they do not count as extra estimated parameters.)</p>
<p>So our <span class="math inline">\(df = 8-5 = 3\)</span>.</p>
<p>The shortcut to estimating the degrees of freedom for a test for independence is:<br />
<span class="math inline">\(df = (r-1)(c-1)\)</span>; which will always give us the same answer (here 3).</p>
<p>We can calculate the p-value in R as:<br />
<code>1-pchisq(w,df)</code> where <span class="math inline">\(w=\chi^2\)</span> – our test statistic, and <span class="math inline">\(df\)</span> are our degrees of freedom.<br />
In our case:<br />
p-value = <code>1-pchisq(8.18,3)</code> = 0.0441</p>
<p>We can also calculate a critical <span class="math inline">\(\chi^2\)</span> value, as we did before.</p>
<p>In short, the chi-squared independence test is the same thing as a goodness of fit test, except the null hypothesis does not specify all the probabilities, but instead specifies the relationship between the marginal and joint probabilities. Consequently, to get expected counts, we have to estimate not only the total count (<span class="math inline">\(n\)</span>) from the data, but also the marginal probabilities. This changes how we calculate both the expected counts as well as the degrees of freedom.</p>
</div>
</div>
<div id="more-than-2-way-contingency-table" class="section level2">
<h2>More than 2-way contingency table</h2>
<p>Chi-squared tests of independence for 2-way contingency tables are by far the most common, but in principle, we can scale the same logic up to contingency tables with more than 2 factors. In practice, I have never seen this done, because (a) it is a test for complete independence of all factors, and a rejection of such a claim of independence is hard to interpret, so people are more interested in the independence of two factors in isolation, and (b) this functionality is rarely built into statistics software.</p>
</div>
<div id="mathematical-rationale" class="section level2">
<h2>Mathematical rationale</h2>
<p>The Chi-squared test is based on the <span class="math inline">\(\chi^2\)</span> distribution, and the Normal approximation to the binomial distribution.</p>
<p>The binomial distribution of the number of successes <span class="math inline">\(k\)</span> out of <span class="math inline">\(n\)</span> attempts (where each attempt <span class="math inline">\(w_i\)</span> is independent and has probability of success <span class="math inline">\(p\)</span>), is written as <span class="math inline">\(k \sim \text{Binomial}(n,p)\)</span>. If we label each success as 1, and each failure as 0, then <span class="math inline">\(k = \sum_{i=1}^n w_i\)</span>. The central limit theorem says that when <span class="math inline">\(n\)</span> is sufficiently large, we can approximate the distribution of <span class="math inline">\(k\)</span> as a Normal distribution with mean <span class="math inline">\(np\)</span> and variance <span class="math inline">\(np(1-p)\)</span> (provided some continuity correction).</p>
<p>If <span class="math inline">\(x_i \sim \text{Normal}(0,1)\)</span>, then the sum of <span class="math inline">\(m\)</span> squared x values is distributed as a chi-squared distribution with <span class="math inline">\(n\)</span> degrees of freedom: <span class="math inline">\(\sum_{i=1}^m x_i^2 \sim \chi^2(m)\)</span>. In other words, the chi-squared distribution is the distribution of <span class="math inline">\(m\)</span> squared z-scores.</p>
<p>The Chi-squared test relies on the normal approximation to the binomial to calculate the z-score of the deviation of the count in each cell compared to that expected under the null hypothesis; then sums these z-scores (this isn’t quite right, but it conveys the intuition).</p>
<p>If the null hypothesis is true, then this sum of z-scored deviations ought to follow a Chi-squared distribution, if the observed statistic is very large compared to the null hypothesis Chi-squared distribution then we can reject the null hypothesis.</p>
<p>(for a more detailed mathematical description of how these notions combine, take a look at the <a href="http://en.wikipedia.org/wiki/Pearson&#39;s_chi-squared_test#Distribution">wikipedia page</a>.</p>
</div>
<div id="limitations" class="section level2">
<h2>Limitations</h2>
<p>The chi-squared test relies on the normal approximation to the Binomial distribution of counts within each cell; the normal approximation holds when the observed and expected counts are large, but breaks down when they are small. I have seen a number of rules of thumb for “how large should the counts be to use a chi-squared test?”. In practice, it seems that folks use the chi-squared test regardless of those rules of thumb. You can look at some of these rules of thumb on <a href="http://en.wikipedia.org/wiki/Pearson&#39;s_chi-squared_test">wikipedia</a>.</p>
<p>Wikipedia suggests using the Yates correction to alter the statistic (when cell counts are too small) to:<br />
<span class="math inline">\(\chi^2_{\text{Yates}} = \sum_{i=1}^c \frac{(|O_{i} - E_{i}|-0.5)^2}{E_{i}}\)</span></p>
<p>Using Yate’s correction is always <em>more conservative</em>, meaning that the probability of Type I error is lower for a given <span class="math inline">\(\alpha\)</span>; this is desirable when counts are low because without the correction the Type I error may end up higher than <span class="math inline">\(\alpha\)</span>. (as a consequence, Yate’s correction makes Type II error higher, and thus lowers power).</p>
<p>The statement “the probability of Type I error is lower for a given <span class="math inline">\(\alpha\)</span>” may be puzzling, because we usually say that <span class="math inline">\(\alpha\)</span> <em>is</em> the probability of Type I error. However, this is only true <em>in theory</em>: when all the assumptions of a given test/model are met. When the assumptions of the test/model are not met, the test statistic does not follow the exact hypothetical distribution, and therefore the Type I error rate ends up different from <span class="math inline">\(\alpha\)</span> – sometimes lower, sometimes higher. Obviously, the deviations from assumptions that increase Type I error rates compared to <span class="math inline">\(\alpha\)</span> are those that we must be more careful of.</p>
<p>In practice, if you have particularly small counts and need to test against some theoretical distribution, I suggest doing resampling to calculate the exact null hypothesis distribution, and compute a p-value without relying on the questionable normal approximation under low cell counts (we will cover variations of this technique in the second semester). Fortunately, R’s <code>chisq-test</code> function warns you when cell counts are small, and suggests doing exactly this. To carry out this Monte Carlo simulation to get a p-value without assuming asymptotically normal behavior from small cell counts, set <code>simulate.p.value=TRUE</code> in <code>chisq.test</code>.</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="chi-squared.html#cb328-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(df<span class="sc">$</span>sex, df<span class="sc">$</span>color), <span class="at">simulate.p.value =</span> T)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with simulated p-value (based on 2000 replicates)
## 
## data:  table(df$sex, df$color)
## X-squared = 8.1782, df = NA, p-value = 0.03698</code></pre>
</div>
<div id="fishers-exact-test" class="section level2">
<h2>Fisher’s “exact” test</h2>
<p>Another variant of the simulation-based chi-squared test <em>for independence</em> that does not rely on a normal approximation is Fisher’s exact test. In R, for a 2x2 contingency table, <code>fisher.test()</code> runs the exact test for independence (based on the hypergeometric distribution), for larger NxM tables it calculates a simulation based probability that these data could have been generated if the categorical variables are indeed independent. Generally, fisher.test is only used if you have a 2x2 table, and even then, rarely.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="chi-squared.html#cb330-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(<span class="fu">table</span>(df<span class="sc">$</span>sex, df<span class="sc">$</span>color))</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  table(df$sex, df$color)
## p-value = 0.04316
## alternative hypothesis: two.sided</code></pre>
<p>(Note that the chi-squared distribution based test, the chi-squared simulated p value, and the simulated p value from the fisher test function all give us slightly different p-values! None of them is more correct than another; I prefer to use the simulated chi-squared test by default.)</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="binomial-test.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="bivariate.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/notes/nhst-chi-squared.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
